tiniest refactor
hyperledger/aries-toolbox pull request #291
Opened 2022-10-31 05:02 UTC by manonthemat

Signed-off-by: Matthias Sieber <matthias.sieber@loxeinc.com>

2022-11-09 20:50 UTC, cjhowland approved these changes
Looks good to me!

2022-11-10 22:22 UTC, manonthemat commented
@cjhowland, thank you for the review.
I'm requesting a re-review as I added the label of a DID in the dropdown and active DID state after attending today's workshop - which by the way, was phenomenal.

2022-11-10 22:23 UTC, manonthemat commented
@frostyfrog when I requested another review after pushing to the already approved PR, you got removed from the reviewers. :thinking:

2022-11-10 22:35 UTC, manonthemat commented
This is what it looks like.

![DID list with labels](https://user-images.githubusercontent.com/5065940/201220447-07e6975a-dd06-42cb-a321-6315bfd66b10.png)

2022-11-14 21:57 UTC, cjhowland requested changes
Hi Matthias! Thanks for attending the workshop and making this useful addition.

It looks as though the syntax `did.metadata?.label` is not supported and the toolbox cannot compile for me locally. Borrowing the syntax from the conditional statement in the `get_name` method in `DidList.vue` seems to fix it.

2022-11-14 21:57 UTC, cjhowland commented on src/renderer/components/AgentBase.vue
> +            :label="did.metadata?.label ? `${did.metadata.label} (${did.did})` : did.did" :value="did">
```suggestion
            :label="'metadata' in did && 'label' in did.metadata ? `${did.metadata.label} (${did.did})` : did.did" :value="did">
```

2022-11-15 15:50 UTC, cjhowland approved these changes

2022-11-16 00:24 UTC, merged